// GENERATED by tools/gen_band_allowlist.py from era-data/band-allowlist.yaml (sha256 c388d2c0bad6) — DO NOT EDIT.
// Regenerate with tools/era-regen.sh. Read by EraBandClassifier (rule 3). Node grants and
// spell_ranks members above a node-granted r1 are deliberately absent: content resolves them.
#pragma once
#include "Define.h"
#include <cstddef>

struct EraBandAllowEntry
{
    uint32 lo;              // inclusive id range
    uint32 hi;
    uint8  eraMask;         // bit = EraId (1 Vanilla, 2 TBC, 4 WotLK)
    uint32 classMask;       // bit = CLASS_* id
    uint32 nodeByEra[3];    // gating node per EraId, 0 = ungated in that era
    char const* note;
};

inline constexpr char const* kEraBandAllowlistHash = "c388d2c0bad6";
inline constexpr size_t kEraBandAllowlistCount = 86;
inline constexpr EraBandAllowEntry kEraBandAllowlist[] =
{
    { 932304, 932304, 0x1, 0x8, { 0, 0, 0 }, "Era Vanilla Hunter marker, trainer ReqAbility anchor" },
    { 948280, 948280, 0x2, 0x8, { 0, 0, 0 }, "Era TBC Hunter marker" },
    { 932305, 932305, 0x4, 0x8, { 0, 0, 0 }, "Era WotLK Hunter marker" },
    { 932300, 932303, 0x1, 0x8, { 0, 0, 0 }, "Scorpid Sting Vanilla clones r1-r4, trainer-taught behind 932304" },
    { 948281, 948281, 0x2, 0x8, { 0, 0, 0 }, "TBC Scorpid Sting clone, trainer-taught behind 948280" },
    { 932416, 932416, 0x1, 0x80, { 0, 0, 0 }, "Vanilla totem marker (trainer 14 anchor)" },
    { 947440, 947440, 0x2, 0x80, { 0, 0, 0 }, "TBC totem marker" },
    { 932417, 932417, 0x4, 0x80, { 0, 0, 0 }, "WotLK totem marker" },
    { 931000, 931000, 0x1, 0x80, { 0, 0, 0 }, "Earthbind Totem Vanilla clone, trainer-taught behind 932416" },
    { 931020, 931025, 0x1, 0x80, { 0, 0, 0 }, "Stoneskin Totem Vanilla clones, trainer-taught behind 932416" },
    { 931040, 931043, 0x1, 0x80, { 0, 0, 0 }, "Strength of Earth Totem Vanilla clones, trainer-taught behind 932416" },
    { 931060, 931065, 0x1, 0x80, { 0, 0, 0 }, "Stoneclaw Totem Vanilla clones, trainer-taught behind 932416" },
    { 931080, 931080, 0x1, 0x80, { 0, 0, 0 }, "Tremor Totem Vanilla clone, trainer-taught behind 932416" },
    { 931100, 931105, 0x1, 0x80, { 0, 0, 0 }, "Searing Totem Vanilla clones, trainer-taught behind 932416" },
    { 931120, 931123, 0x1, 0x80, { 0, 0, 0 }, "Magma Totem Vanilla clones, trainer-taught behind 932416" },
    { 931140, 931143, 0x1, 0x80, { 0, 0, 0 }, "Flametongue Totem Vanilla clones, trainer-taught behind 932416" },
    { 931160, 931162, 0x1, 0x80, { 0, 0, 0 }, "Frost Resistance Totem Vanilla clones, trainer-taught behind 932416" },
    { 931180, 931184, 0x1, 0x80, { 0, 0, 0 }, "Healing Stream Totem Vanilla clones, trainer-taught behind 932416" },
    { 931200, 931203, 0x1, 0x80, { 0, 0, 0 }, "Mana Spring Totem Vanilla clones, trainer-taught behind 932416" },
    { 931220, 931222, 0x1, 0x80, { 0, 0, 0 }, "Fire Resistance Totem Vanilla clones, trainer-taught behind 932416" },
    { 931240, 931240, 0x1, 0x80, { 0, 0, 0 }, "Poison Cleansing Totem Vanilla clone, trainer-taught behind 932416" },
    { 931260, 931260, 0x1, 0x80, { 0, 0, 0 }, "Disease Cleansing Totem Vanilla clone, trainer-taught behind 932416" },
    { 931280, 931280, 0x1, 0x80, { 0, 0, 0 }, "Grounding Totem Vanilla clone, trainer-taught behind 932416" },
    { 931300, 931302, 0x1, 0x80, { 0, 0, 0 }, "Nature Resistance Totem Vanilla clones, trainer-taught behind 932416" },
    { 931320, 931321, 0x1, 0x80, { 0, 0, 0 }, "Grace of Air Totem Vanilla clones, trainer-taught behind 932416" },
    { 931340, 931342, 0x1, 0x80, { 0, 0, 0 }, "Windwall Totem Vanilla clones, trainer-taught behind 932416" },
    { 931353, 931357, 0x1, 0x80, { 0, 0, 0 }, "Fire Nova Totem Vanilla summons r1-5, trainer-taught behind 932416" },
    { 931363, 931365, 0x1, 0x80, { 0, 0, 0 }, "Windfury Totem Vanilla summons r1-3, trainer-taught behind 932416" },
    { 931390, 931390, 0x1, 0x80, { 0, 0, 0 }, "Sentry Totem Vanilla clone, trainer-taught behind 932416" },
    { 947000, 947000, 0x2, 0x80, { 0, 0, 0 }, "Earthbind Totem TBC clone, trainer-taught behind 947440" },
    { 947020, 947027, 0x2, 0x80, { 0, 0, 0 }, "Stoneskin Totem TBC clones r1-8, trainer-taught behind 947440" },
    { 947030, 947035, 0x2, 0x80, { 0, 0, 0 }, "Strength of Earth Totem TBC clones r1-6, trainer-taught behind 947440" },
    { 947050, 947056, 0x2, 0x80, { 0, 0, 0 }, "Stoneclaw Totem TBC clones r1-7, trainer-taught behind 947440" },
    { 947070, 947070, 0x2, 0x80, { 0, 0, 0 }, "Tremor Totem TBC clone, trainer-taught behind 947440" },
    { 947080, 947080, 0x2, 0x80, { 0, 0, 0 }, "Earth Elemental Totem TBC clone, trainer-taught behind 947440" },
    { 947090, 947090, 0x2, 0x80, { 0, 0, 0 }, "Searing Totem TBC clone r7 (r1-6 are grant-stock), trainer-taught behind 947440" },
    { 947115, 947119, 0x2, 0x80, { 0, 0, 0 }, "Magma Totem TBC clones r1-5, trainer-taught behind 947440" },
    { 947120, 947124, 0x2, 0x80, { 0, 0, 0 }, "Flametongue Totem TBC clones r1-5, trainer-taught behind 947440" },
    { 947140, 947143, 0x2, 0x80, { 0, 0, 0 }, "Frost Resistance Totem TBC clones r1-4, trainer-taught behind 947440" },
    { 947150, 947150, 0x2, 0x80, { 0, 0, 0 }, "Fire Elemental Totem TBC clone, trainer-taught behind 947440" },
    { 947170, 947175, 0x2, 0x80, { 0, 0, 0 }, "Healing Stream Totem TBC clones r1-6, trainer-taught behind 947440" },
    { 947190, 947194, 0x2, 0x80, { 0, 0, 0 }, "Mana Spring Totem TBC clones r1-5, trainer-taught behind 947440" },
    { 947200, 947203, 0x2, 0x80, { 0, 0, 0 }, "Fire Resistance Totem TBC clones r1-4, trainer-taught behind 947440" },
    { 947210, 947210, 0x2, 0x80, { 0, 0, 0 }, "Poison Cleansing Totem TBC clone, trainer-taught behind 947440" },
    { 947220, 947220, 0x2, 0x80, { 0, 0, 0 }, "Disease Cleansing Totem TBC clone, trainer-taught behind 947440" },
    { 947240, 947240, 0x2, 0x80, { 0, 0, 0 }, "Grounding Totem TBC clone, trainer-taught behind 947440" },
    { 947250, 947253, 0x2, 0x80, { 0, 0, 0 }, "Nature Resistance Totem TBC clones r1-4, trainer-taught behind 947440" },
    { 947260, 947260, 0x2, 0x80, { 0, 0, 0 }, "Sentry Totem TBC clone, trainer-taught behind 947440" },
    { 947270, 947272, 0x2, 0x80, { 0, 0, 0 }, "Grace of Air Totem TBC clones r1-3, trainer-taught behind 947440" },
    { 947280, 947283, 0x2, 0x80, { 0, 0, 0 }, "Windwall Totem TBC clones r1-4, trainer-taught behind 947440" },
    { 947290, 947290, 0x2, 0x80, { 0, 0, 0 }, "Tranquil Air Totem TBC clone, trainer-taught behind 947440" },
    { 947300, 947300, 0x2, 0x80, { 0, 0, 0 }, "Wrath of Air Totem TBC clone, trainer-taught behind 947440" },
    { 947310, 947316, 0x2, 0x80, { 0, 0, 0 }, "Fire Nova Totem TBC clones r1-7, trainer-taught behind 947440" },
    { 947330, 947334, 0x2, 0x80, { 0, 0, 0 }, "Windfury Totem TBC clones r1-5, trainer-taught behind 947440" },
    { 947441, 947441, 0x2, 0x80, { 0, 0, 0 }, "Windfury Weapon TBC clone r5 (r1-4 are grant-stock), trainer-taught behind 947440" },
    { 932749, 932749, 0x1, 0x4, { 0, 0, 0 }, "Vanilla seal-training marker, trainer ReqAbility1 anchor" },
    { 946078, 946078, 0x2, 0x4, { 0, 0, 0 }, "TBC seal-training marker" },
    { 932634, 932639, 0x1, 0x4, { 0, 0, 0 }, "Seal of the Crusader Vanilla clones, trainer-taught behind 932749" },
    { 932700, 932707, 0x1, 0x4, { 0, 0, 0 }, "Seal of Righteousness Vanilla clones, trainer-taught behind 932749" },
    { 932724, 932728, 0x1, 0x4, { 0, 0, 0 }, "Seal of Justice + Seal of Light Vanilla clones, trainer-taught behind 932749" },
    { 932737, 932739, 0x1, 0x4, { 0, 0, 0 }, "Seal of Wisdom Vanilla clones, trainer-taught behind 932749" },
    { 946000, 946008, 0x2, 0x4, { 0, 0, 0 }, "Seal of Righteousness TBC clones r1-9, trainer-taught behind 946078" },
    { 946034, 946038, 0x2, 0x4, { 0, 0, 0 }, "Seal of Light TBC clones r1-5, trainer-taught behind 946078" },
    { 946050, 946053, 0x2, 0x4, { 0, 0, 0 }, "Seal of Wisdom TBC clones r1-4, trainer-taught behind 946078" },
    { 946063, 946070, 0x2, 0x4, { 0, 0, 0 }, "Seal of Justice TBC r1 + Seal of the Crusader TBC r1-7, trainer-taught behind 946078" },
    { 946079, 946080, 0x2, 0x4, { 0, 0, 0 }, "Seal of Justice TBC r2 + Seal of Blood 946080 (Horde), trainer-taught behind 946078" },
    { 946084, 946084, 0x2, 0x4, { 0, 0, 0 }, "Seal of Vengeance TBC (Alliance), trainer-taught behind 946078 — the JoB/JoV carriers 946081-083 / 946085-086 are script-cast and deliberately absent (never in character_spell)" },
    { 932668, 932670, 0x3, 0x4, { 0, 0, 0 }, "Lay on Hands clones — Vanilla trainer-taught, TBC reconcile-granted (reused substrate)" },
    { 932746, 932746, 0x3, 0x4, { 0, 0, 0 }, "the single Judgement button — Vanilla trainer-taught, TBC reconcile-granted" },
    { 932930, 932930, 0x3, 0x200, { 0, 0, 0 }, "Era Pre-Wrath Cast Times marker — patch 0019 Corruption 2 s cast; Vanilla AND TBC" },
    { 932994, 932994, 0x1, 0x200, { 0, 0, 0 }, "Era Vanilla Warlock marker, Create-stone trainer anchor" },
    { 948410, 948410, 0x2, 0x200, { 0, 0, 0 }, "Era TBC Warlock marker, Create-stone trainer anchor" },
    { 932939, 932939, 0x4, 0x200, { 0, 0, 0 }, "Era WotLK Warlock marker" },
    { 932922, 932928, 0x1, 0x200, { 0, 0, 0 }, "Vanilla Create Firestone/Spellstone clones behind 932994" },
    { 948420, 948428, 0x2, 0x200, { 0, 0, 0 }, "TBC Create Firestone/Spellstone clones behind 948410" },
    { 932513, 932513, 0x3, 0x800, { 0, 0, 0 }, "Enrage clone, reconcile-granted at L12 (version swap of stock 5229)" },
    { 946280, 946280, 0x2, 0x800, { 0, 20135, 0 }, "Heart of the Wild bear-stamina marker (patch 0023), granted while node 20135 is spent" },
    { 946261, 946263, 0x2, 0x800, { 0, 20141, 0 }, "Mangle (Cat) r1 partner of node 20141 + trained r2/r3" },
    { 946265, 946265, 0x2, 0x800, { 0, 20161, 0 }, "hidden Tree of Life form passive, partner of node 20161's form grant" },
    { 932950, 932950, 0x1, 0x20, { 18144, 0, 0 }, "Vampiric Embrace heal proc-passive (Vanilla)" },
    { 948032, 948032, 0x2, 0x20, { 0, 20555, 0 }, "Vampiric Embrace heal proc-passive (TBC)" },
    { 948029, 948030, 0x2, 0x20, { 0, 20513, 0 }, "Prayer of Spirit TBC r1-2 — own spell_ranks root (948029), trainer-taught off the node-granted Divine Spirit r1 948024" },
    { 947539, 947539, 0x2, 0x2, { 0, 20343, 0 }, "Rampage crit-watcher passive, granted while node 20343 is spent" },
    { 932845, 932845, 0x3, 0x2, { 0, 0, 0 }, "Defensive Stance era correction (-10% dmg done / +30% threat), reconcile-granted to every era warrior" },
    { 932846, 932846, 0x3, 0x2, { 0, 0, 0 }, "Berserker Stance era correction (+10% dmg taken / no threat modifier), reconcile-granted to every era warrior" },
    { 932847, 932847, 0x3, 0x2, { 0, 0, 0 }, "Battle Stance era correction (no threat modifier / no armor penetration), reconcile-granted to every era warrior" },
};
