import importlib.util as _ilu, pathlib, subprocess, sys, os
import pytest

_spec = _ilu.spec_from_file_location("gen_band_allowlist", "tools/gen_band_allowlist.py")
GB = _ilu.module_from_spec(_spec); _spec.loader.exec_module(GB)

GOOD = """\
entries:
  - ids: [932749]
    eras: [vanilla]
    classes: [paladin]
    kind: marker
    note: seal-training marker
  - range: [946000, 946026]
    eras: [tbc]
    classes: [paladin]
    kind: trainer
    note: TBC seal chains below SoC r1
  - ids: [946261, 946262, 946263]
    eras: [tbc]
    classes: [druid]
    kind: partner
    node: {tbc: 20141}
    note: Mangle (Cat) partner chain
  - ids: [932513]
    eras: [vanilla, tbc]
    classes: [druid]
    kind: level-grant
    note: Enrage clone
stranded: [920040, 921745]
"""

def _write(tmp_path, text):
    p = tmp_path / "band-allowlist.yaml"; p.write_text(text); return p

def test_load_good(tmp_path):
    al = GB.load_allowlist(_write(tmp_path, GOOD))
    assert len(al.entries) == 4 and al.stranded == [920040, 921745]
    e = al.entries[2]
    assert (e.lo, e.hi) == (946261, 946263)
    assert e.era_mask == 0b010 and e.class_mask == (1 << 11)
    assert e.node_by_era == [0, 20141, 0]
    assert al.entries[3].era_mask == 0b011

def test_emit_header_shape(tmp_path):
    al = GB.load_allowlist(_write(tmp_path, GOOD))
    h = GB.emit_header(al)
    assert h.startswith("// GENERATED by tools/gen_band_allowlist.py")
    assert "DO NOT EDIT" in h
    assert 'inline constexpr char const* kEraBandAllowlistHash = "' in h
    assert "{ 946261, 946263, 0x2, 0x800, { 0, 20141, 0 }, \"Mangle (Cat) partner chain\" }," in h
    assert "{ 932513, 932513, 0x3, 0x800, { 0, 0, 0 }, \"Enrage clone\" }," in h
    assert "inline constexpr size_t kEraBandAllowlistCount = 4;" in h

def test_hash_tracks_yaml_bytes(tmp_path):
    a = GB.emit_header(GB.load_allowlist(_write(tmp_path, GOOD)))
    b = GB.emit_header(GB.load_allowlist(_write(tmp_path, GOOD.replace("Enrage clone", "Enrage"))))
    assert GB.HASH_RE.search(a).group(1) != GB.HASH_RE.search(b).group(1)

@pytest.mark.parametrize("bad,msg", [
    (GOOD.replace("eras: [vanilla]\n    classes: [paladin]\n    kind: marker", "eras: [wrath]\n    classes: [paladin]\n    kind: marker"), "unknown era"),
    (GOOD.replace("classes: [paladin]\n    kind: marker", "classes: [pally]\n    kind: marker"), "unknown class"),
    (GOOD.replace("  - ids: [932749]\n", "  - ids: [932749]\n    range: [1, 2]\n"), "both ids and range"),
    (GOOD.replace("range: [946000, 946026]", "range: [946026, 946000]"), "range hi < lo"),
    (GOOD.replace("ids: [932749]", "ids: [12345]"), "outside the band"),
    (GOOD.replace("node: {tbc: 20141}", "node: {vanilla: 20141}"), "node for an unlisted era"),
    (GOOD.replace("kind: marker", "kind: thing"), "unknown kind"),
    (GOOD.replace("    note: seal-training marker\n", ""), "note"),
    (GOOD.replace("stranded: [920040, 921745]", "stranded: [920040, 932749]"), "stranded id 932749 is allowlisted"),
])
def test_rejects(tmp_path, bad, msg):
    with pytest.raises(GB.AllowlistError) as ei:
        GB.load_allowlist(_write(tmp_path, bad))
    assert msg in str(ei.value)

def test_cli_writes_header(tmp_path):
    y = _write(tmp_path, GOOD); out = tmp_path / "EraBandAllowlist.gen.h"
    r = subprocess.run([sys.executable, "tools/gen_band_allowlist.py", str(y), "-o", str(out)],
                       capture_output=True, text=True, cwd=os.getcwd())
    assert r.returncode == 0, r.stderr
    assert out.read_text().count("{ 9") == 4

_aspec = _ilu.spec_from_file_location("era_audit", "tools/era_audit.py")
A = _ilu.module_from_spec(_aspec); _aspec.loader.exec_module(A)

SQL_FIXTURE = """\
INSERT INTO `era_talent` (id,eraId,classId,tab,tierRow,col,maxRank,prereqTalentId,prereqPoints) VALUES
(20141,1,11,1,3,1,1,0,0),
(18701,0,11,0,1,1,1,0,0);
INSERT INTO `era_talent_rank` (talentId,`rank`,grantedSpellId) VALUES
(20141,1,946258),
(18701,1,932505);
INSERT INTO `spell_ranks` (`first_spell_id`,`spell_id`,`rank`) VALUES
  (946258, 946258, 1),
  (946258, 946259, 2),
  (932505, 932505, 1),
  (932505, 932507, 2),
  (946261, 946261, 1),
  (946261, 946262, 2);
INSERT INTO `trainer_spell`
  (`TrainerId`,`SpellId`,`MoneyCost`,`ReqSkillLine`,`ReqSkillRank`,`ReqAbility1`,`ReqAbility2`,`ReqAbility3`,`ReqLevel`,`VerifiedBuild`) VALUES
  (16, 946259, 100, 0, 0, 946258, 0, 0, 20, 0),
  (16, 946262, 100, 0, 0, 946261, 0, 0, 20, 0),
  (16, 931000, 100, 0, 0, 932416, 0, 0,  6, 0);
INSERT INTO `spell_dbc` (`ID`, `Category`, `Name_Lang_enUS`) VALUES
(946258, 0, 'Mangle (Bear)'),
(946259, 0, 'Mangle (Bear)'),
(946261, 0, 'Mangle (Cat)'),
(946262, 0, 'Mangle (Cat)'),
(931000, 0, 'Stoneskin, Totem'),
(932416, 0, 'Era: Vanilla Totems'),
(932505, 0, 'Nature''s Grasp'),
(932507, 0, 'Nature''s Grasp');
"""

AL_COMPLETE = """\
entries:
  - ids: [946261, 946262]
    eras: [tbc]
    classes: [druid]
    kind: partner
    node: {tbc: 20141}
    note: Mangle (Cat) partner chain
  - ids: [931000]
    eras: [vanilla]
    classes: [shaman]
    kind: trainer
    note: Stoneskin totem, trainer-taught behind 932416
  - ids: [932416]
    eras: [vanilla]
    classes: [shaman]
    kind: marker
    note: Vanilla totem marker
stranded: [920040]
"""

def _audit(tmp_path, monkeypatch, allow_text, sql_text=SQL_FIXTURE):
    sqldir = tmp_path / "sql"; sqldir.mkdir()
    (sqldir / "2026_01_01_00_fixture.sql").write_text(sql_text)
    al = tmp_path / "band-allowlist.yaml"; al.write_text(allow_text)
    monkeypatch.setattr(A, "_MODULE_SQL_DIR", sqldir)
    monkeypatch.setattr(A, "_BAND_ALLOWLIST", al)
    findings = []
    A.check_band_ownership(findings)
    return findings

def test_band_ownership_clean(tmp_path, monkeypatch):
    assert _audit(tmp_path, monkeypatch, AL_COMPLETE) == []

def test_band_ownership_flags_unallowlisted_trainer_chain(tmp_path, monkeypatch):
    f = _audit(tmp_path, monkeypatch, AL_COMPLETE.replace("  - ids: [946261, 946262]\n    eras: [tbc]\n    classes: [druid]\n    kind: partner\n    node: {tbc: 20141}\n    note: Mangle (Cat) partner chain\n", ""))
    assert any("946262" in x and "trainer_spell" in x for x in f)
    assert any("946261" in x and "ReqAbility1" in x for x in f)

def test_band_ownership_flags_missing_marker(tmp_path, monkeypatch):
    f = _audit(tmp_path, monkeypatch, AL_COMPLETE.replace("  - ids: [932416]\n    eras: [vanilla]\n    classes: [shaman]\n    kind: marker\n    note: Vanilla totem marker\n", ""))
    assert any("932416" in x and "ReqAbility1" in x for x in f)

def test_band_ownership_flags_node_grant_overlap(tmp_path, monkeypatch):
    bad = AL_COMPLETE.replace("ids: [946261, 946262]", "range: [946258, 946262]")
    f = _audit(tmp_path, monkeypatch, bad)
    assert any("946258" in x and "node grant" in x for x in f)

def test_band_ownership_flags_allowlisted_id_without_spell_dbc(tmp_path, monkeypatch):
    f = _audit(tmp_path, monkeypatch, AL_COMPLETE.replace("ids: [931000]", "ids: [931001]"))
    assert any("931001" in x and "spell_dbc" in x for x in f)

def test_band_ownership_flags_stranded_that_is_classifiable(tmp_path, monkeypatch):
    f = _audit(tmp_path, monkeypatch, AL_COMPLETE.replace("stranded: [920040]", "stranded: [932505]"))
    assert any("932505" in x and "stranded" in x for x in f)

def test_band_ownership_flags_out_of_band_chain_root(tmp_path, monkeypatch):
    sql = SQL_FIXTURE + "INSERT INTO `spell_ranks` (`first_spell_id`,`spell_id`,`rank`) VALUES\n  (12345, 12345, 1),\n  (12345, 946270, 2);\n"
    f = _audit(tmp_path, monkeypatch, AL_COMPLETE, sql)
    assert any("946270" in x and "outside the band" in x for x in f)

def test_band_ownership_flags_chain_member_overlap(tmp_path, monkeypatch):
    entry = ("  - ids: [946259]\n"
             "    eras: [tbc]\n"
             "    classes: [druid]\n"
             "    kind: trainer\n"
             "    note: Mangle Bear r2\n")
    bad = AL_COMPLETE.replace("stranded:", entry + "stranded:")
    f = _audit(tmp_path, monkeypatch, bad)
    assert any("946259" in x and "rank above node-granted root 946258" in x for x in f)

def test_module_rows_semicolon_inside_string(tmp_path, monkeypatch):
    sqldir = tmp_path / "sql"; sqldir.mkdir()
    (sqldir / "2026_01_01_00_fixture.sql").write_text(
        "INSERT INTO `spell_dbc` (`ID`, `Category`, `Name_Lang_enUS`) VALUES\n"
        "(946002, 0, 'ends with ; -- x'),\n"
        "(946003, 0, 'next');\n"
    )
    monkeypatch.setattr(A, "_MODULE_SQL_DIR", sqldir)
    ids = {r[0] for r in A._module_rows("spell_dbc")}
    assert 946002 in ids and 946003 in ids
